# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e6de83f4882da04d7b3a50c5c092040878f8058920aee201e844f4c8e7b2192ed36beb4e64ccd8a69610c5776dd0aefd4c0f22c90a4872892d23568e3e0e2e2

test:
  secret_key_base: cba729ae4ed1a7e17faf71e9e0b6d93d6d79d1e36e164642d93287c763c89db4302e5864465a58d20e44d0838c0617ec82e6df30a6f4c01b443f003acb86cbf7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
